name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [11, 15, 16]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          ./gradlew -Pjvm_target=${{ matrix.jdk }} printProps
          ./gradlew -Pjvm_target=${{ matrix.jdk }} --info build
